---
- name: "Render config and quadlet files ({{ service_name }})"
  ansible.builtin.include_tasks: setup.yml

- name: "Pull image and start service ({{ service_name }})"
  ansible.builtin.include_tasks: containers.yml
