---
extends: default

ignore:
  - .venv/
  - collections/
  - "**/vault.yml"
  - "**/vault_*.yml"

rules:
  line-length:
    max: 160
    level: warning
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  braces:
    max-spaces-inside: 1
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
  truthy:
    allowed-values: ["true", "false", "yes", "no"]
    check-keys: false
